### ISSUE TITLE
Backtrace and Deprecation with PHP 8.1

### ISSUE THREAD

**Issue by jdcoats** [Cacti/plugin_routerconfigs#122]
Manual backups work but this is printed.
```
2023/01/26 13:45:37 - CMDPHP PHP ERROR Backtrace: (/plugins/routerconfigs/router-download.php[133]:plugin_routerconfigs_download(), /plugins/routerconfigs/include/functions.php[165]:plugin_routerconfigs_download_config(), /plugins/routerconfigs/include/functions.php[495]:PHPConnection->Disconnect(), /plugins/routerconfigs/classes/PHPConnection.php[232]:PHPConnection->DoCommand(), /plugins/routerconfigs/classes/PHPConnection.php[276]:preg_replace(), CactiErrorHandler())
2023/01/26 13:45:37 - ERROR PHP DEPRECATED in Plugin 'routerconfigs': preg_replace(): Passing null to parameter #3 ($subject) of type array|string is deprecated in file: /var/www/localhost/htdocs/cacti/plugins/routerconfigs/classes/PHPConnection.php on line: 276
2023/01/26 13:45:36 - CMDPHP PHP ERROR WARNING Backtrace: (/plugins/routerconfigs/router-download.php[133]:plugin_routerconfigs_download(), /plugins/routerconfigs/include/functions.php[165]:plugin_routerconfigs_download_config(), /plugins/routerconfigs/include/functions.php[495]:PHPConnection->Disconnect(), /plugins/routerconfigs/classes/PHPConnection.php[232]:PHPConnection->DoCommand(), /plugins/routerconfigs/classes/PHPConnection.php[275]:PHPConnection->GetResponse(), /plugins/routerconfigs/classes/PHPConnection.php[289]:fgets(), CactiErrorHandler())
2023/01/26 13:45:36 - ERROR PHP WARNING in Plugin 'routerconfigs': fgets(): Failure 'transport read' (-43) in file: /var/www/localhost/htdocs/cacti/plugins/routerconfigs/classes/PHPConnection.php on line: 289
```

**Comment by TheWitness** [comment]
Should be resolved.  Please report back.

**Comment by jdcoats** [comment]
That broke it good, search does not work and cant get to other tabs
```
2023/01/27 12:37:19 - CMDPHP WARNING: Page:router-backups.php?tab=backups Generated a Fatal Error:500
2023/01/27 12:37:19 - SYSTEM WARNING: Primary Admin account notifications disabled! Unable to send administrative Email.
2023/01/27 12:37:19 - CMDPHP ERRORS DETECTED - DISABLING PLUGIN 'routerconfigs'
2023/01/27 12:37:19 - CMDPHP PHP ERROR Backtrace: (CactiShutdownHandler())
2023/01/27 12:37:19 - ERROR PHP ERROR in Plugin 'routerconfigs': Uncaught TypeError: sizeof(): Argument #1 ($value) must be of type Countable\|array, bool given in /var/www/localhost/htdocs/cacti/plugins/routerconfigs/router-backups.php:327 Stack trace: #0 /var/www/localhost/htdocs/cacti/plugins/routerconfigs/router-backups.php(41): show_devices() #1 {main} thrown in file: /var/www/localhost/htdocs/cacti/plugins/routerconfigs/router-backups.php on line: 327
2023/01/27 12:37:19 - CMDPHP SQL Backtrace: (/plugins/routerconfigs/router-backups.php[41]:show_devices(), /plugins/routerconfigs/router-backups.php[171]:db_fetch_cell_prepared(), /lib/database.php[568]:db_execute_prepared())
2023/01/27 12:37:19 - CMDPHP ERROR: A DB Cell Failed!, Error: Array to string conversion
2023/01/27 12:37:19 - CMDPHP SQL Backtrace: (/plugins/routerconfigs/router-backups.php[41]:show_devices(), /plugins/routerconfigs/router-backups.php[164]:db_fetch_assoc_prepared(), /lib/database.php[697]:db_execute_prepared())
2023/01/27 12:37:19 - CMDPHP ERROR: A DB Row Failed!, Error: Array to string conversion
2023/01/27 12:37:04 - CMDPHP WARNING: Page:router-backups.php?tab=backups Generated a Fatal Error:500
2023/01/27 12:37:04 - SYSTEM WARNING: Primary Admin account notifications disabled! Unable to send administrative Email.
2023/01/27 12:37:04 - CMDPHP ERRORS DETECTED - DISABLING PLUGIN 'routerconfigs'
2023/01/27 12:37:04 - CMDPHP PHP ERROR Backtrace: (CactiShutdownHandler())
2023/01/27 12:37:04 - ERROR PHP ERROR in Plugin 'routerconfigs': Uncaught TypeError: sizeof(): Argument #1 ($value) must be of type Countable\|array, bool given in /var/www/localhost/htdocs/cacti/plugins/routerconfigs/router-backups.php:327 Stack trace: #0 /var/www/localhost/htdocs/cacti/plugins/routerconfigs/router-backups.php(41): show_devices() #1 {main} thrown in file: /var/www/localhost/htdocs/cacti/plugins/routerconfigs/router-backups.php on line: 327
2023/01/27 12:37:04 - CMDPHP SQL Backtrace: (/plugins/routerconfigs/router-backups.php[41]:show_devices(), /plugins/routerconfigs/router-backups.php[171]:db_fetch_cell_prepared(), /lib/database.php[568]:db_execute_prepared())
2023/01/27 12:37:04 - CMDPHP ERROR: A DB Cell Failed!, Error: Array to string conversion
2023/01/27 12:37:04 - CMDPHP SQL Backtrace: (/plugins/routerconfigs/router-backups.php[41]:show_devices(), /plugins/routerconfigs/router-backups.php[164]:db_fetch_assoc_prepared(), /lib/database.php[697]:db_execute_prepared())
2023/01/27 12:37:04 - CMDPHP ERROR: A DB Row Failed!, Error: Array to string conversion
2023/01/27 12:36:40 - CMDPHP WARNING: Page:router-backups.php?tab=backups Generated a Fatal Error:500
2023/01/27 12:36:40 - SYSTEM WARNING: Primary Admin account notifications disabled! Unable to send administrative Email.
2023/01/27 12:36:40 - CMDPHP ERRORS DETECTED - DISABLING PLUGIN 'routerconfigs'
2023/01/27 12:36:40 - CMDPHP PHP ERROR Backtrace: (CactiShutdownHandler())
2023/01/27 12:36:40 - ERROR PHP ERROR in Plugin 'routerconfigs': Uncaught TypeError: sizeof(): Argument #1 ($value) must be of type Countable\|array, bool given in /var/www/localhost/htdocs/cacti/plugins/routerconfigs/router-backups.php:327 Stack trace: #0 /var/www/localhost/htdocs/cacti/plugins/routerconfigs/router-backups.php(41): show_devices() #1 {main} thrown in file: /var/www/localhost/htdocs/cacti/plugins/routerconfigs/router-backups.php on line: 327
2023/01/27 12:36:40 - CMDPHP SQL Backtrace: (/plugins/routerconfigs/router-backups.php[41]:show_devices(), /plugins/routerconfigs/router-backups.php[171]:db_fetch_cell_prepared(), /lib/database.php[568]:db_execute_prepared())
2023/01/27 12:36:40 - CMDPHP ERROR: A DB Cell Failed!, Error: Array to string conversion
2023/01/27 12:36:40 - CMDPHP SQL Backtrace: (/plugins/routerconfigs/router-backups.php[41]:show_devices(), /plugins/routerconfigs/router-backups.php[164]:db_fetch_assoc_prepared(), /lib/database.php[697]:db_execute_prepared())
2023/01/27 12:36:40 - CMDPHP ERROR: A DB Row Failed!, Error: Array to string conversion
2023/01/27 12:36:30 - SYSTEM WARNING: Primary Admin account notifications disabled! Unable to send administrative Email.
2023/01/27 12:36:30 - CMDPHP WARNING: Page:router-backups.php?tab=backups Generated a Fatal Error:500
2023/01/27 12:36:30 - SYSTEM WARNING: Primary Admin account notifications disabled! Unable to send administrative Email.
2023/01/27 12:36:30 - CMDPHP ERRORS DETECTED - DISABLING PLUGIN 'routerconfigs'
2023/01/27 12:36:30 - CMDPHP PHP ERROR Backtrace: (CactiShutdownHandler())
2023/01/27 12:36:30 - ERROR PHP ERROR in Plugin 'routerconfigs': Uncaught TypeError: sizeof(): Argument #1 ($value) must be of type Countable\|array, bool given in /var/www/localhost/htdocs/cacti/plugins/routerconfigs/router-backups.php:327 Stack trace: #0 /var/www/localhost/htdocs/cacti/plugins/routerconfigs/router-backups.php(41): show_devices() #1 {main} thrown in file: /var/www/localhost/htdocs/cacti/plugins/routerconfigs/router-backups.php on line: 327
2023/01/27 12:36:30 - CMDPHP SQL Backtrace: (/plugins/routerconfigs/router-backups.php[41]:show_devices(), /plugins/routerconfigs/router-backups.php[171]:db_fetch_cell_prepared(), /lib/database.php[568]:db_execute_prepared())
2023/01/27 12:36:30 - CMDPHP ERROR: A DB Cell Failed!, Error: Array to string conversion
2023/01/27 12:36:30 - CMDPHP SQL Backtrace: (/plugins/routerconfigs/router-backups.php[41]:show_devices(), /plugins/routerconfigs/router-backups.php[164]:db_fetch_assoc_prepared(), /lib/database.php[697]:db_execute_prepared())
2023/01/27 12:36:30 - CMDPHP ERROR: A DB Row Failed!, Error: Array to string conversion
```

**Comment by TheWitness** [comment]
Cool.  Give me a few minutes.  I took a half day off to prepare a bunch of plugin releases.  So, I'll get this fixed in a jiffy.

**Comment by TheWitness** [comment]
Okay, try again :)

**Comment by jdcoats** [comment]
When I do a backup I still get this.
```
2023/01/27 14:21:43 - CMDPHP PHP ERROR WARNING Backtrace: (/plugins/routerconfigs/router-download.php[133]:plugin_routerconfigs_download(), /plugins/routerconfigs/include/functions.php[165]:plugin_routerconfigs_download_config(), /plugins/routerconfigs/include/functions.php[495]:PHPConnection->Disconnect(), /plugins/routerconfigs/classes/PHPConnection.php[247]:PHPConnection->DoCommand(), /plugins/routerconfigs/classes/PHPConnection.php[297]:PHPConnection->GetResponse(), /plugins/routerconfigs/classes/PHPConnection.php[321]:fgets(), CactiErrorHandler())
2023/01/27 14:21:43 - ERROR PHP WARNING in Plugin 'routerconfigs': fgets(): Failure 'transport read' (-43) in file: /var/www/localhost/htdocs/cacti/plugins/routerconfigs/classes/PHPConnection.php on line: 321
```

**Comment by TheWitness** [comment]
Grr ;)

**Comment by TheWitness** [comment]
Is this for all of them or just some?
