### ISSUE TITLE
Possible loop while sending commands to switch

### ISSUE THREAD

**Issue by seppeel** [Cacti/plugin_routerconfigs#24]
As described here:
https://forums.cacti.net/viewtopic.php?p=270719#p270719

Steps i do:
1. Create new device with name "whatever" while real hostname is "SW-DW-OSN1" (it will be changed with first backup. Device type used is default "Cisco IOS"
2. Do a backup -> Backup is OK. Device Hostname is changed from "whatever" to "SW-DW-OSN1"
  -> The Backup Count under "Devices" is now "Current - Backups (1)"
  -> When i move to "Backups" the Backup is NOT displayed (-> you wont be able to "Compare" it)
3. Do a second Backup -> Backup does NOT work and will Timeout.

DEBUG:
```
0copy run tftp
Address or name of remote host []? Destination filename [sw-dw-osn1-confg]? SW-DW-OSN1#SW-DW-OSN1#SW-DW-OSN1#SW-DW-OSN1#SW-DW-OSN1#SW-DW-OSN1#SW-DW-OSN1#SW-DW-OSN1#SW-DW-OSN1#SW-DW-OSN1#SW-DW-OSN1#SW-DW-OSN1#SW-DW-OSN1#SW-DW-OSN1#SW-DW-OSN1#SW-DW-OSN1#SW-DW-OSN1#SW-DW-OSN1#SW-DW-OSN1#SW-DW-OSN1#SW-DW-OSN1#SW-DW-OSN1#SW-DW-OSN1#SW-DW-OSN1#SW-DW-OSN1#SW-DW-OSN1#SW-DW-OSN1#SW-DW-OSN1#SW-DW-OSN1#SW-DW-OSN1#SW-DW-OSN1#
```

Important Note:
When i change the Hostname back to "whatever" or anything else, the Backup will work again as described in step 2.

**Comment by seppeel** [comment]
i now know the reason for this behavior:
the directory Name must not be the same as the description/hostname.
when you try

copy run tftp://192.168.160.152/SW-DW-OSN1

and "SW-DW-OSN1" already exists as directory -> It fails.

A possible workaround would be to append a ".config" to the filenames.

**Comment by netniV** [comment]
That would make more sense since it makes the files themselves more easily identifiable.  However, if there is any archive history holding the filename, there would need to be a process to identify and update these to the new format.

**Comment by seppeel** [comment]
I now created a bunch of devices to backup and discovered loop :)
One uses an enable password. i created a new auth account and defined the password.

i did a manuel cli backup to give debug infos:

```
root@gmh-log01:/var/www/cacti/plugins/routerconfigs# php -q router-download.php --force --debug --devices=17
28-02-2018 11:26:15 - RCONFIG NOTICE: Starting manual backup of 1 devices
28-02-2018 11:26:15 - RCONFIG DEBUG: SQL: SELECT * FROM plugin_routerconfigs_devices WHERE enabled = 'on' AND id IN (17)
28-02-2018 11:26:15 - RCONFIG DEBUG: Attempting download for <switch>
28-02-2018 11:26:15 - RCONFIG DEBUG: Base64 decoded: a:3:{i:1014060807;i:309414344;s:8:"password";s:8:"(8: chars)";i:75800125;i:555807293;}
28-02-2018 11:26:15 - RCONFIG DEBUG: Base64 decoded: a:3:{i:112302712;i:998963947;s:8:"password";s:12:"(12: chars)";i:1506939848;i:245143412;}
28-02-2018 11:26:15 - RCONFIG 192.168.165.12 -> DEBUG: Attempting to connect via SSH
28-02-2018 11:26:15 - RCONFIG 192.168.165.12 (SSH) -> DEBUG: Creating SSH(Server: <ip>, User: <user>, Password: (8 chars), Enablepw: (12 chars), Devicetype: {"id":"1","name":"Cisco IOS","username":"username:","password":"password:","copytftp":"copy run tftp","version":"show version","confirm":"y","forceconfirm":"","checkendinconfig":"on"}
28-02-2018 11:26:15 - RCONFIG 192.168.165.12 (SSH) -> DEBUG: okay: logged in...
28-02-2018 11:26:15 - RCONFIG 192.168.165.12 (SSH) -> DEBUG: Connected via ssh
28-02-2018 11:26:15 - RCONFIG 192.168.165.12 (SSH) -> NOTICE: Ensuring process is enabled
28-02-2018 11:26:16 - RCONFIG 192.168.165.12 (SSH) -> DEBUG: Found Prompt (Normal)
28-02-2018 11:26:16 - RCONFIG 192.168.165.12 (SSH) -> DEBUG: Attempt 0 of 10 to find prompt
28-02-2018 11:26:16 - RCONFIG 192.168.165.12 (SSH) -> DEBUG: Sending enable command
28-02-2018 11:26:16 - RCONFIG 192.168.165.12 (SSH) -> DEBUG: Found Prompt (Password)
28-02-2018 11:26:16 - RCONFIG 192.168.165.12 (SSH) -> DEBUG: Found Prompt (Password)
28-02-2018 11:26:18 - RCONFIG 192.168.165.12 (SSH) -> DEBUG: Timeout of 1 seconds has been reached
28-02-2018 11:26:18 - RCONFIG 192.168.165.12 (SSH) -> DEBUG: Found Prompt (Password)
28-02-2018 11:26:20 - RCONFIG 192.168.165.12 (SSH) -> DEBUG: Timeout of 1 seconds has been reached
28-02-2018 11:26:20 - RCONFIG 192.168.165.12 (SSH) -> DEBUG: Found Prompt (Normal)
28-02-2018 11:26:22 - RCONFIG 192.168.165.12 (SSH) -> DEBUG: Timeout of 1 seconds has been reached
28-02-2018 11:26:22 - RCONFIG 192.168.165.12 (SSH) -> DEBUG: Found Prompt (Password)
28-02-2018 11:26:22 - RCONFIG 192.168.165.12 (SSH) -> DEBUG: Found Prompt (Password)
28-02-2018 11:26:24 - RCONFIG 192.168.165.12 (SSH) -> DEBUG: Timeout of 1 seconds has been reached
28-02-2018 11:26:24 - RCONFIG 192.168.165.12 (SSH) -> DEBUG: Found Prompt (Password)
28-02-2018 11:26:24 - RCONFIG 192.168.165.12 (SSH) -> DEBUG: Found Prompt (Normal)
28-02-2018 11:26:26 - RCONFIG 192.168.165.12 (SSH) -> DEBUG: Timeout of 1 seconds has been reached
28-02-2018 11:26:26 - RCONFIG 192.168.165.12 (SSH) -> DEBUG: Found Prompt (Password)
28-02-2018 11:26:26 - RCONFIG 192.168.165.12 (SSH) -> DEBUG: Found Prompt (Password)
28-02-2018 11:26:28 - RCONFIG 192.168.165.12 (SSH) -> DEBUG: Timeout of 1 seconds has been reached
28-02-2018 11:26:28 - RCONFIG 192.168.165.12 (SSH) -> DEBUG: Found Prompt (Password)
28-02-2018 11:26:28 - RCONFIG 192.168.165.12 (SSH) -> DEBUG: Found Prompt (Normal)
28-02-2018 11:26:30 - RCONFIG 192.168.165.12 (SSH) -> DEBUG: Timeout of 1 seconds has been reached
28-02-2018 11:26:30 - RCONFIG 192.168.165.12 (SSH) -> DEBUG: Found Prompt (Password)
28-02-2018 11:26:30 - RCONFIG 192.168.165.12 (SSH) -> DEBUG: Found Prompt (Password)
28-02-2018 11:26:32 - RCONFIG 192.168.165.12 (SSH) -> DEBUG: Timeout of 1 seconds has been reached
28-02-2018 11:26:32 - RCONFIG 192.168.165.12 (SSH) -> DEBUG: Found Prompt (Password)
28-02-2018 11:26:32 - RCONFIG 192.168.165.12 (SSH) -> DEBUG: Found Prompt (Normal)
28-02-2018 11:26:34 - RCONFIG 192.168.165.12 (SSH) -> DEBUG: Timeout of 1 seconds has been reached
[.................]
```

As you noticed, i removed **sensitive** information from the debug log ;-)

Seems like the script doesnt recognize the need for an enable password here?

**Comment by netniV** [comment]
That looks like it's getting stuck inside the EnsureEnabled() function. I'll take a look i the next hour or so when I'm on my lunch break. Also, what version are you using?

**Comment by seppeel** [comment]
cacti 1.1.36 + current dev branch routerconfigs

**Comment by seppeel** [comment]
it would be a good idea to define a timeout because i just realized that routerconfigs wa looping around on our core switch for the last 4 hours 💃  :D

**Comment by netniV** [comment]
It's only supposed to try up to 10 or 30 times depending on where it is

**Comment by netniV** [comment]
OK, I found the issue, the loop counter was outside the loop for that one part.  I'm just going to push through an update which should help.

**Comment by netniV** [comment]
See the latest update.

**Comment by netniV** [comment]
v1.3.2 is now available.

**Comment by seppeel** [comment]
We now see, that we are in enabled mode :)

```
02-03-2018 14:45:40 - RCONFIG 10.140.72.5 (SSH) -> DEBUG: okay: logged in...
02-03-2018 14:45:40 - RCONFIG 10.140.72.5 (SSH) -> DEBUG: Connected via ssh
02-03-2018 14:45:40 - RCONFIG 10.140.72.5 (SSH) -> NOTICE: Ensuring process is enabled
02-03-2018 14:45:40 - RCONFIG 10.140.72.5 (SSH) -> DEBUG: Found Prompt (Normal)
02-03-2018 14:45:40 - RCONFIG 10.140.72.5 (SSH) -> DEBUG: Attempt 0 of 10 to find prompt
02-03-2018 14:45:40 - RCONFIG 10.140.72.5 (SSH) -> DEBUG: Sending enable command
02-03-2018 14:45:40 - RCONFIG 10.140.72.5 (SSH) -> DEBUG: Found Prompt (Password)
02-03-2018 14:45:41 - RCONFIG 10.140.72.5 (SSH) -> DEBUG: Found Prompt (Enabled)
02-03-2018 14:45:41 - RCONFIG 10.140.72.5 (SSH) -> DEBUG: Ok we are in enabled mode
02-03-2018 14:45:43 - RCONFIG 10.140.72.5 (SSH) -> DEBUG: Timeout of 1 seconds has been reached
02-03-2018 14:45:45 - RCONFIG 10.140.72.5 (SSH) -> DEBUG: Timeout of 1 seconds has been reached
02-03-2018 14:45:47 - RCONFIG 10.140.72.5 (SSH) -> DEBUG: Timeout of 1 seconds has been reached

```

**Comment by netniV** [comment]
Is it timing out after that?  Can you run with the -b option to see the buffer output?

**Comment by seppeel** [comment]
It works, i just didnt wait long enough for the timeout. i will now check telnet connections.

**Comment by seppeel** [comment]
```
02-03-2018 15:10:50 - RCONFIG 192.168.165.17 (Telnet) -> Looking for username:
02-03-2018 15:10:52 - RCONFIG 192.168.165.17 (Telnet) -> DEBUG: Timeout of 1 seconds has been reached
02-03-2018 15:10:52 - RCONFIG 192.168.165.17 (Telnet) -> DEBUG: Sending username: <user>
02-03-2018 15:10:52 - RCONFIG 192.168.165.17 (Telnet) -> DEBUG: Buffer: <user>
02-03-2018 15:10:52 - RCONFIG 192.168.165.17 (Telnet) -> DEBUG: Buffer:
02-03-2018 15:10:52 - RCONFIG 192.168.165.17 (Telnet) -> DEBUG: Buffer: Password:
02-03-2018 15:10:52 - RCONFIG 192.168.165.17 (Telnet) -> DEBUG: Found Prompt (Password)
02-03-2018 15:10:54 - RCONFIG 192.168.165.17 (Telnet) -> DEBUG: Timeout of 1 seconds has been reached
02-03-2018 15:10:56 - RCONFIG 192.168.165.17 (Telnet) -> DEBUG: Timeout of 1 seconds has been reached
02-03-2018 15:10:58 - RCONFIG 192.168.165.17 (Telnet) -> DEBUG: Timeout of 1 seconds has been reached
02-03-2018 15:11:00 - RCONFIG 192.168.165.17 (Telnet) -> DEBUG: Timeout of 1 seconds has been reached
02-03-2018 15:11:02 - RCONFIG 192.168.165.17 (Telnet) -> DEBUG: Timeout of 1 seconds has been reached
02-03-2018 15:11:04 - RCONFIG 192.168.165.17 (Telnet) -> DEBUG: Timeout of 1 seconds has been reached
02-03-2018 15:11:06 - RCONFIG 192.168.165.17 (Telnet) -> DEBUG: Timeout of 1 seconds has been reached
02-03-2018 15:11:08 - RCONFIG 192.168.165.17 (Telnet) -> DEBUG: Timeout of 1 seconds has been reached
02-03-2018 15:11:10 - RCONFIG 192.168.165.17 (Telnet) -> DEBUG: Timeout of 1 seconds has been reached
02-03-2018 15:11:10 - RCONFIG ERROR: Failed to Connect to Device 'SWT-GMH-ASP10' using connection type: telnet
02-03-2018 15:11:10 - RCONFIG NOTICE: Failed to download for SWT-GMH-ASP10
02-03-2018 15:11:10 - RCONFIG WARNING: 0 Devices Backed Up and 1 Devices Failed in 21 seconds
02-03-2018 15:11:10 - RCONFIG DEBUG: 0 devices backed up successfully.
02-03-2018 15:11:10 - RCONFIG DEBUG: 1 devices failed to backup.
02-03-2018 15:11:10 - RCONFIG DEBUG: These devices failed to backup
02-03-2018 15:11:10 - RCONFIG DEBUG: ------------------------------
02-03-2018 15:11:10 - RCONFIG DEBUG: SWT-GMH-ASP10 - ERROR: Failed to Connect to Device 'SWT-GMH-ASP10' using connection type: telnet
02-03-2018 15:11:21 - RCONFIG STATS: Time:31.58 Downloaded:0 Failed:1
root@gmh-log01:/var/www/cacti/plugins/routerconfigs#

```

It doesnt send the password after prompt, but the prompt is recognized.

**Comment by netniV** [comment]
Thanks, I'll look into that.

**Comment by netniV** [comment]
Ah, I've been making most code case-insensitive when it comes to prompt detection etc.  However, the password one on Telnet was still a strpos not a stripos.  I wonder if your prompt is in the wrong case.  This should be in v1.3.3

**Comment by cigamit** [comment]
This is merged now.  Please close if resolved.

**Comment by seppeel** [comment]
generally all devices are working now. with telnet and enable password -> everything ok.
i only have one device with uses which uses telnet and enable password which is not working. i dont see the difference right now between this device and other devices which are working.
log looks like this:

```
05-03-2018 09:21:56 - RCONFIG 10.20.2.10 (Telnet) -> DEBUG: Buffer: User Access Verification
05-03-2018 09:21:56 - RCONFIG 10.20.2.10 (Telnet) -> DEBUG: Buffer:
05-03-2018 09:21:56 - RCONFIG 10.20.2.10 (Telnet) -> DEBUG: Buffer:
05-03-2018 09:21:56 - RCONFIG 10.20.2.10 (Telnet) -> DEBUG: Buffer:
05-03-2018 09:21:57 - RCONFIG 10.20.2.10 (Telnet) -> DEBUG: Buffer: Username: ÿþ ÿúÿðÿþ'ÿý
05-03-2018 09:21:57 - RCONFIG 10.20.2.10 (Telnet) -> Looking for username:
05-03-2018 09:21:59 - RCONFIG 10.20.2.10 (Telnet) -> DEBUG: Timeout of 1 seconds has been reached
05-03-2018 09:21:59 - RCONFIG 10.20.2.10 (Telnet) -> DEBUG: Sending username: <user>
05-03-2018 09:21:59 - RCONFIG 10.20.2.10 (Telnet) -> DEBUG: Buffer: <user>
05-03-2018 09:21:59 - RCONFIG 10.20.2.10 (Telnet) -> DEBUG: Buffer:
05-03-2018 09:21:59 - RCONFIG 10.20.2.10 (Telnet) -> DEBUG: Buffer: Password:
05-03-2018 09:21:59 - RCONFIG 10.20.2.10 (Telnet) -> DEBUG: Found Prompt (Password)
05-03-2018 09:21:59 - RCONFIG 10.20.2.10 (Telnet) -> DEBUG: Found prompt 'Password:', Sending password: (8 chars)
05-03-2018 09:21:59 - RCONFIG 10.20.2.10 (Telnet) -> DEBUG: Buffer:
05-03-2018 09:21:59 - RCONFIG 10.20.2.10 (Telnet) -> DEBUG: Buffer:
05-03-2018 09:22:00 - RCONFIG 10.20.2.10 (Telnet) -> DEBUG: Buffer: <hostname>>
05-03-2018 09:22:00 - RCONFIG 10.20.2.10 (Telnet) -> DEBUG: Found Prompt (Normal)
05-03-2018 09:22:00 - RCONFIG 10.20.2.10 (Telnet) -> NOTICE: Connected via telnet
05-03-2018 09:22:00 - RCONFIG 10.20.2.10 (Telnet) -> NOTICE: Ensuring process is enabled
05-03-2018 09:22:02 - RCONFIG 10.20.2.10 (Telnet) -> DEBUG: Timeout of 1 seconds has been reached
05-03-2018 09:22:02 - RCONFIG 10.20.2.10 (Telnet) -> DEBUG: Attempt 0 of 10 to find prompt
05-03-2018 09:22:02 - RCONFIG 10.20.2.10 (Telnet) -> DEBUG: Buffer:
05-03-2018 09:22:02 - RCONFIG 10.20.2.10 (Telnet) -> DEBUG: Buffer:
05-03-2018 09:22:02 - RCONFIG 10.20.2.10 (Telnet) -> DEBUG: Buffer: <hostname>>
05-03-2018 09:22:02 - RCONFIG 10.20.2.10 (Telnet) -> DEBUG: Found Prompt (Normal)
05-03-2018 09:22:02 - RCONFIG 10.20.2.10 (Telnet) -> DEBUG: Attempt 1 of 10 to find prompt
05-03-2018 09:22:02 - RCONFIG 10.20.2.10 (Telnet) -> DEBUG: Sending enable command
05-03-2018 09:22:02 - RCONFIG 10.20.2.10 (Telnet) -> DEBUG: Buffer: en
05-03-2018 09:22:02 - RCONFIG 10.20.2.10 (Telnet) -> DEBUG: Buffer:
05-03-2018 09:22:03 - RCONFIG 10.20.2.10 (Telnet) -> DEBUG: Buffer: Password:
05-03-2018 09:22:03 - RCONFIG 10.20.2.10 (Telnet) -> DEBUG: Found Prompt (Password)
05-03-2018 09:22:03 - RCONFIG 10.20.2.10 (Telnet) -> DEBUG: Buffer:
05-03-2018 09:22:03 - RCONFIG 10.20.2.10 (Telnet) -> DEBUG: Buffer:
05-03-2018 09:22:03 - RCONFIG 10.20.2.10 (Telnet) -> DEBUG: Buffer: Password:
05-03-2018 09:22:03 - RCONFIG 10.20.2.10 (Telnet) -> DEBUG: Found Prompt (Password)
05-03-2018 09:22:06 - RCONFIG 10.20.2.10 (Telnet) -> DEBUG: Timeout of 1 seconds has been reached
05-03-2018 09:22:06 - RCONFIG 10.20.2.10 (Telnet) -> DEBUG: Buffer:
05-03-2018 09:22:06 - RCONFIG 10.20.2.10 (Telnet) -> DEBUG: Buffer:
05-03-2018 09:22:06 - RCONFIG 10.20.2.10 (Telnet) -> DEBUG: Buffer: Password:
05-03-2018 09:22:06 - RCONFIG 10.20.2.10 (Telnet) -> DEBUG: Found Prompt (Password)
05-03-2018 09:22:08 - RCONFIG 10.20.2.10 (Telnet) -> DEBUG: Timeout of 1 seconds has been reached
05-03-2018 09:22:08 - RCONFIG 10.20.2.10 (Telnet) -> DEBUG: Buffer:
05-03-2018 09:22:08 - RCONFIG 10.20.2.10 (Telnet) -> DEBUG: Buffer:
05-03-2018 09:22:08 - RCONFIG 10.20.2.10 (Telnet) -> DEBUG: Buffer: % Bad secrets
05-03-2018 09:22:08 - RCONFIG 10.20.2.10 (Telnet) -> DEBUG: Buffer:
05-03-2018 09:22:08 - RCONFIG 10.20.2.10 (Telnet) -> DEBUG: Buffer:
05-03-2018 09:22:08 - RCONFIG 10.20.2.10 (Telnet) -> DEBUG: Buffer:
05-03-2018 09:22:08 - RCONFIG 10.20.2.10 (Telnet) -> DEBUG: Buffer: <hostname>>
05-03-2018 09:22:08 - RCONFIG 10.20.2.10 (Telnet) -> DEBUG: Found Prompt (Normal)
05-03-2018 09:22:11 - RCONFIG 10.20.2.10 (Telnet) -> DEBUG: Timeout of 1 seconds has been reached
05-03-2018 09:22:11 - RCONFIG 10.20.2.10 (Telnet) -> DEBUG: Buffer: en
05-03-2018 09:22:11 - RCONFIG 10.20.2.10 (Telnet) -> DEBUG: Buffer:
05-03-2018 09:22:11 - RCONFIG 10.20.2.10 (Telnet) -> DEBUG: Buffer: Password:
05-03-2018 09:22:11 - RCONFIG 10.20.2.10 (Telnet) -> DEBUG: Found Prompt (Password)
05-03-2018 09:22:11 - RCONFIG 10.20.2.10 (Telnet) -> DEBUG: Buffer:
05-03-2018 09:22:11 - RCONFIG 10.20.2.10 (Telnet) -> DEBUG: Buffer:
05-03-2018 09:22:12 - RCONFIG 10.20.2.10 (Telnet) -> DEBUG: Buffer: Password:
05-03-2018 09:22:12 - RCONFIG 10.20.2.10 (Telnet) -> DEBUG: Found Prompt (Password)
05-03-2018 09:22:14 - RCONFIG 10.20.2.10 (Telnet) -> DEBUG: Timeout of 1 seconds has been reached
05-03-2018 09:22:14 - RCONFIG 10.20.2.10 (Telnet) -> DEBUG: Buffer:
05-03-2018 09:22:14 - RCONFIG 10.20.2.10 (Telnet) -> DEBUG: Buffer:
05-03-2018 09:22:15 - RCONFIG 10.20.2.10 (Telnet) -> DEBUG: Buffer: Password:
05-03-2018 09:22:15 - RCONFIG 10.20.2.10 (Telnet) -> DEBUG: Found Prompt (Password)
05-03-2018 09:22:15 - RCONFIG 10.20.2.10 (Telnet) -> DEBUG: Buffer:
05-03-2018 09:22:15 - RCONFIG 10.20.2.10 (Telnet) -> DEBUG: Buffer:
05-03-2018 09:22:15 - RCONFIG 10.20.2.10 (Telnet) -> DEBUG: Buffer: % Bad secrets
05-03-2018 09:22:15 - RCONFIG 10.20.2.10 (Telnet) -> DEBUG: Buffer:
05-03-2018 09:22:15 - RCONFIG 10.20.2.10 (Telnet) -> DEBUG: Buffer:
05-03-2018 09:22:15 - RCONFIG 10.20.2.10 (Telnet) -> DEBUG: Buffer:
05-03-2018 09:22:15 - RCONFIG 10.20.2.10 (Telnet) -> DEBUG: Buffer: <hostname>>
05-03-2018 09:22:15 - RCONFIG 10.20.2.10 (Telnet) -> DEBUG: Found Prompt (Normal)
05-03-2018 09:22:17 - RCONFIG 10.20.2.10 (Telnet) -> DEBUG: Timeout of 1 seconds has been reached
05-03-2018 09:22:17 - RCONFIG 10.20.2.10 (Telnet) -> DEBUG: Buffer: en
05-03-2018 09:22:17 - RCONFIG 10.20.2.10 (Telnet) -> DEBUG: Buffer:
^C
```

 i will try to investigate that further, but i already double checked the authentication data. the enable password should work.

**Comment by netniV** [comment]
Don't worry, I'm updating the prompt detection code to be more robust.  In fact, I'm also pushing a change that makes the rest of the code use a common prompt detection to work out what is needed next.

**Comment by netniV** [comment]
So, test again once 1.3.4 is push out.

**Comment by seppeel** [comment]
```
06-03-2018 13:40:17 - RCONFIG 10.20.2.10 (SSH) -> DEBUG: Buffer: <hostname>>
06-03-2018 13:40:17 - RCONFIG 10.20.2.10 (SSH) -> DEBUG: Found Prompt (Normal)
06-03-2018 13:40:17 - RCONFIG 10.20.2.10 (SSH) -> DEBUG: Attempt 1 of 10 to find prompt
06-03-2018 13:40:17 - RCONFIG 10.20.2.10 (SSH) -> DEBUG: Sending enable command
PHP Fatal error:  Uncaught Error: Class 'LoginPrompt' not found in /var/www/cacti/plugins/routerconfigs/functions.php:1064
Stack trace:
#0 /var/www/cacti/plugins/routerconfigs/functions.php(487): PHPConnection->EnsureEnabled()
#1 /var/www/cacti/plugins/routerconfigs/functions.php(154): plugin_routerconfigs_download_config(Array, 1520340016, true, false)
#2 /var/www/cacti/plugins/routerconfigs/router-download.php(133): plugin_routerconfigs_download(false, true, Array, true, false)
#3 {main}
  thrown in /var/www/cacti/plugins/routerconfigs/functions.php on line 1064
root@gmh-log01:/var/www/cacti/plugins/routerconfigs#
```

**Comment by netniV** [comment]
`*cough* update *cough*`

**Comment by seppeel** [comment]
:-)

```
06-03-2018 14:55:45 - RCONFIG 10.20.2.10 (SSH) -> DEBUG: Buffer: <hostname>>
06-03-2018 14:55:45 - RCONFIG 10.20.2.10 (SSH) -> DEBUG: Found Prompt (Normal)
06-03-2018 14:55:45 - RCONFIG 10.20.2.10 (SSH) -> DEBUG: Attempt 1 of 10 to find prompt
06-03-2018 14:55:45 - RCONFIG 10.20.2.10 (SSH) -> DEBUG: Sending enable command
06-03-2018 14:55:45 - RCONFIG 10.20.2.10 (SSH) -> DEBUG: Buffer: en
06-03-2018 14:55:45 - RCONFIG 10.20.2.10 (SSH) -> DEBUG: Buffer:
06-03-2018 14:55:45 - RCONFIG 10.20.2.10 (SSH) -> DEBUG: Buffer: Password:
06-03-2018 14:55:45 - RCONFIG 10.20.2.10 (SSH) -> DEBUG: Found Prompt (Password)
06-03-2018 14:55:45 - RCONFIG 10.20.2.10 (SSH) -> DEBUG: Buffer:
06-03-2018 14:55:45 - RCONFIG 10.20.2.10 (SSH) -> DEBUG: Buffer:
06-03-2018 14:55:45 - RCONFIG 10.20.2.10 (SSH) -> DEBUG: Buffer: Password:
06-03-2018 14:55:45 - RCONFIG 10.20.2.10 (SSH) -> DEBUG: Found Prompt (Password)
06-03-2018 14:55:47 - RCONFIG 10.20.2.10 (SSH) -> DEBUG: Timeout of 1 seconds has been reached
06-03-2018 14:55:49 - RCONFIG 10.20.2.10 (SSH) -> DEBUG: Timeout of 1 seconds has been reached
06-03-2018 14:55:51 - RCONFIG 10.20.2.10 (SSH) -> DEBUG: Timeout of 1 seconds has been reached
06-03-2018 14:55:53 - RCONFIG 10.20.2.10 (SSH) -> DEBUG: Timeout of 1 seconds has been reached
06-03-2018 14:55:55 - RCONFIG 10.20.2.10 (SSH) -> DEBUG: Timeout of 1 seconds has been reached
06-03-2018 14:55:57 - RCONFIG 10.20.2.10 (SSH) -> DEBUG: Timeout of 1 seconds has been reached
06-03-2018 14:55:59 - RCONFIG 10.20.2.10 (SSH) -> DEBUG: Timeout of 1 seconds has been reached
06-03-2018 14:56:01 - RCONFIG 10.20.2.10 (SSH) -> DEBUG: Timeout of 1 seconds has been reached
06-03-2018 14:56:03 - RCONFIG 10.20.2.10 (SSH) -> DEBUG: Timeout of 1 seconds has been reached
06-03-2018 14:56:03 - RCONFIG 10.20.2.10 (SSH) -> Process is now NOT enabled
PHP Warning:  Missing argument 2 for plugin_routerconfigs_save_debug(), called in /var/www/cacti/plugins/routerconfigs/functions.php on line 490 and defined in /var/www/cacti/plugins/routerconfigs/functions.php on line 823
PHP Notice:  Undefined variable: connection in /var/www/cacti/plugins/routerconfigs/functions.php on line 824
PHP Fatal error:  Uncaught Error: Call to a member function getDebug() on null in /var/www/cacti/plugins/routerconfigs/functions.php:824
Stack trace:
#0 /var/www/cacti/plugins/routerconfigs/functions.php(490): plugin_routerconfigs_save_debug(Array)
#1 /var/www/cacti/plugins/routerconfigs/functions.php(154): plugin_routerconfigs_download_config(Array, 1520344543, true, false)
#2 /var/www/cacti/plugins/routerconfigs/router-download.php(133): plugin_routerconfigs_download(false, true, Array, true, false)
#3 {main}
  thrown in /var/www/cacti/plugins/routerconfigs/functions.php on line 824
root@gmh-log01:/var/www/cacti/plugins/routerconfigs#
```

**Comment by netniV** [comment]
I take it the wrong password was against this device?

**Comment by netniV** [comment]
Fixed.

**Comment by seppeel** [comment]
Triple checked credentials. also tried Telnet and SSH.
The only differences in comparison to other devices i see:
- the hostname on this device is in lower case
- the hostname on this device does not end with a number


```
06-03-2018 15:06:44 - RCONFIG 10.20.2.10 (SSH) -> DEBUG: Attempt 1 of 10 to find prompt
06-03-2018 15:06:45 - RCONFIG 10.20.2.10 (SSH) -> DEBUG: Buffer:
06-03-2018 15:06:45 - RCONFIG 10.20.2.10 (SSH) -> DEBUG: Buffer:
06-03-2018 15:06:45 - RCONFIG 10.20.2.10 (SSH) -> DEBUG: Buffer: <hostname>>
06-03-2018 15:06:45 - RCONFIG 10.20.2.10 (SSH) -> DEBUG: Found Prompt (Normal)
06-03-2018 15:06:45 - RCONFIG 10.20.2.10 (SSH) -> DEBUG: Attempt 2 of 10 to find prompt
06-03-2018 15:06:45 - RCONFIG 10.20.2.10 (SSH) -> DEBUG: Sending enable command
06-03-2018 15:06:45 - RCONFIG 10.20.2.10 (SSH) -> DEBUG: Buffer:
06-03-2018 15:06:45 - RCONFIG 10.20.2.10 (SSH) -> DEBUG: Buffer:
06-03-2018 15:06:45 - RCONFIG 10.20.2.10 (SSH) -> DEBUG: Buffer: <hostname>>
06-03-2018 15:06:45 - RCONFIG 10.20.2.10 (SSH) -> DEBUG: Found Prompt (Normal)
06-03-2018 15:06:45 - RCONFIG 10.20.2.10 (SSH) -> DEBUG: Buffer:
06-03-2018 15:06:45 - RCONFIG 10.20.2.10 (SSH) -> DEBUG: Buffer:
06-03-2018 15:06:45 - RCONFIG 10.20.2.10 (SSH) -> DEBUG: Buffer: <hostname>>
06-03-2018 15:06:45 - RCONFIG 10.20.2.10 (SSH) -> DEBUG: Found Prompt (Normal)
06-03-2018 15:06:46 - RCONFIG 10.20.2.10 (SSH) -> DEBUG: Buffer: e
06-03-2018 15:06:46 - RCONFIG 10.20.2.10 (SSH) -> DEBUG: Buffer: n
06-03-2018 15:06:46 - RCONFIG 10.20.2.10 (SSH) -> DEBUG: Buffer:
06-03-2018 15:06:46 - RCONFIG 10.20.2.10 (SSH) -> DEBUG: Buffer:
06-03-2018 15:06:46 - RCONFIG 10.20.2.10 (SSH) -> DEBUG: Buffer: Password:
06-03-2018 15:06:46 - RCONFIG 10.20.2.10 (SSH) -> DEBUG: Found Prompt (Password)
06-03-2018 15:06:48 - RCONFIG 10.20.2.10 (SSH) -> DEBUG: Timeout of 1 seconds has been reached
06-03-2018 15:06:48 - RCONFIG 10.20.2.10 (SSH) -> DEBUG: Enable login failed
06-03-2018 15:06:48 - RCONFIG 10.20.2.10 (SSH) -> DEBUG: Buffer:
06-03-2018 15:06:48 - RCONFIG 10.20.2.10 (SSH) -> DEBUG: Buffer:
06-03-2018 15:06:48 - RCONFIG 10.20.2.10 (SSH) -> DEBUG: Buffer: Password:
06-03-2018 15:06:48 - RCONFIG 10.20.2.10 (SSH) -> DEBUG: Found Prompt (Password)
06-03-2018 15:06:48 - RCONFIG 10.20.2.10 (SSH) -> Process is now NOT enabled
06-03-2018 15:06:48 - RCONFIG NOTICE: Failed to download for <hostname>
06-03-2018 15:06:48 - RCONFIG WARNING: 0 Devices Backed Up, 1 Devices Failed, 1 Disabled (ignored) in 7 seconds
06-03-2018 15:06:48 - RCONFIG DEBUG: 0 devices backed up successfully.
06-03-2018 15:06:48 - RCONFIG DEBUG: 1 devices failed to backup.
06-03-2018 15:06:48 - RCONFIG DEBUG: 1 devices disabled from backup.
06-03-2018 15:06:49 - RCONFIG STATS: Time:7.62 Downloaded:0 Failed:1
root@gmh-log01:/var/www/cacti/plugins/routerconfigs#
```

**Comment by netniV** [comment]
So I've updated the "Enable login failed" to display the resulting error code number that was got whilst sending the command.

**Comment by seppeel** [comment]
We now created a user with privilege 15 (no enable needed)
 -> It works.

**Comment by netniV** [comment]
Cool. So is this closed now too?

**Comment by seppeel** [comment]
For me, yes.
If someone has this problem again with a device, a new issue can be opened ;-)
