### ISSUE TITLE
backup error (function.php line 1228)

### ISSUE THREAD

**Issue by seppeel** [Cacti/plugin_routerconfigs#55]
Hey @netniV :-)

Since yesterday routerconfigs gets disabled after scheduled backup. I did a manual backup and it stopped with this error:

```
13.03.2018 14:00:34 - RCONFIG 192.168.160.163 (SSH) -> DEBUG: Line: TFTP put operation was successful
13.03.2018 14:00:34 - RCONFIG 192.168.160.163 (SSH) -> DEBUG: Line: Copy complete, now saving to disk (please wait)...
13.03.2018 14:00:34 - RCONFIG 192.168.160.163 (SSH) -> DEBUG: Line: SW-GMH-NXGREEN-2#
13.03.2018 14:00:34 - RCONFIG 192.168.160.163 (SSH) -> DEBUG: Result: (0)
13.03.2018 14:00:34 - RCONFIG 192.168.160.163 (SSH) -> DEBUG: Checking for valid incoming file at /routerconfigs/SW-GMH-NXGREEN-2
13.03.2018 14:00:34 - RCONFIG 192.168.160.163 (SSH) -> DEBUG: Attempting to open file at /routerconfigs/SW-GMH-NXGREEN-2
13.03.2018 14:00:34 - RCONFIG 192.168.160.163 (SSH) -> DEBUG: Configuration end check was not performed
13.03.2018 14:00:34 - RCONFIG 192.168.160.163 (SSH) -> DEBUG: --> terminal length 0
13.03.2018 14:00:34 - RCONFIG 192.168.160.163 (SSH) -> DEBUG: Found Prompt (Enabled)
13.03.2018 14:00:34 - RCONFIG 192.168.160.163 (SSH) -> DEBUG: --> terminal pager 0
13.03.2018 14:00:34 - RCONFIG 192.168.160.163 (SSH) -> DEBUG: Found Prompt (Enabled)
13.03.2018 14:00:34 - RCONFIG 192.168.160.163 (SSH) -> DEBUG: --> show version
13.03.2018 14:00:35 - RCONFIG 192.168.160.163 (SSH) -> DEBUG: Found Prompt (Colon)
PHP Fatal error:  Uncaught Error: Undefined class constant 'Colon' in /var/www/cacti/plugins/routerconfigs/functions.php:1228
Stack trace:
#0 /var/www/cacti/plugins/routerconfigs/functions.php(1163): PHPConnection->GetResponse('show version\r\r\n...', NULL)
#1 /var/www/cacti/plugins/routerconfigs/functions.php(679): PHPConnection->DoCommand('show version', 'show version\r\r\n...')
#2 /var/www/cacti/plugins/routerconfigs/functions.php(154): plugin_routerconfigs_download_config(Array, 1520945939, false, false)
#3 /var/www/cacti/plugins/routerconfigs/router-download.php(133): plugin_routerconfigs_download(false, true, Array, false, false)
#4 {main}
  thrown in /var/www/cacti/plugins/routerconfigs/functions.php on line 1228
```

Looks related to #47 . The day before i did a "git pull" and got your last changes from "Mar 8, 2018". In these commits you changed the line 1228 in functions.php So it looks like it has to do something with these changes.

Greetings!

**Comment by netniV** [comment]
If you git pull again, it should already be fixed 👍

**Comment by seppeel** [comment]
```
13.03.2018 14:20:21 - RCONFIG NOTICE: 42 Devices Backed Up, 0 Devices Failed, 0 Disabled (ignored) in 183 seconds
13.03.2018 14:20:21 - RCONFIG DEBUG: 42 devices backed up successfully.
13.03.2018 14:20:21 - RCONFIG DEBUG: 0 devices failed to backup.
13.03.2018 14:20:37 - RCONFIG STATS: Time:198.83 Downloaded:42 Failed:0
```

:-)
Closed.
